-- MySQL Script generated by MySQL Workbench
-- Fri Feb  5 15:43:43 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LogiWeb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LogiWeb` ;

-- -----------------------------------------------------
-- Schema LogiWeb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LogiWeb` DEFAULT CHARACTER SET utf8 ;
USE `LogiWeb` ;

-- -----------------------------------------------------
-- Table `LogiWeb`.`truck`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LogiWeb`.`truck` ;

CREATE TABLE IF NOT EXISTS `LogiWeb`.`truck` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` CHAR(7) NOT NULL,
  `driver_shift_size` TINYINT UNSIGNED NOT NULL,
  `capacity` FLOAT UNSIGNED NOT NULL,
  `status` ENUM('OK', 'DEFECTIVE') NOT NULL DEFAULT 'OK',
  `current_city` VARCHAR(51) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idtruck_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `trucknumber_UNIQUE` (`number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LogiWeb`.`route_point`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LogiWeb`.`route_point` ;

CREATE TABLE IF NOT EXISTS `LogiWeb`.`route_point` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(51) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LogiWeb`.`delivery_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LogiWeb`.`delivery_order` ;

CREATE TABLE IF NOT EXISTS `LogiWeb`.`delivery_order` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `status` ENUM('DONE', 'PROGRESS', 'CREATED') NOT NULL DEFAULT 'CREATED',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LogiWeb`.`cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LogiWeb`.`cargo` ;

CREATE TABLE IF NOT EXISTS `LogiWeb`.`cargo` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `weight` FLOAT UNSIGNED NOT NULL,
  `status` ENUM('PREPARED', 'SHIPPED', 'DELIVERED') NOT NULL DEFAULT 'PREPARED',
  `truck_id` BIGINT UNSIGNED NULL,
  `shipment_point_id` BIGINT UNSIGNED NOT NULL,
  `discharge_point_id` BIGINT UNSIGNED NOT NULL,
  `order_id` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idcargo_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `truck_id_idx` (`truck_id` ASC) VISIBLE,
  INDEX `shipment_point_id_idx` (`shipment_point_id` ASC) VISIBLE,
  INDEX `discharge_point_id_idx` (`discharge_point_id` ASC) VISIBLE,
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `truck_id`
    FOREIGN KEY (`truck_id`)
    REFERENCES `LogiWeb`.`truck` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `shipment_point_id`
    FOREIGN KEY (`shipment_point_id`)
    REFERENCES `LogiWeb`.`route_point` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `discharge_point_id`
    FOREIGN KEY (`discharge_point_id`)
    REFERENCES `LogiWeb`.`route_point` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `LogiWeb`.`delivery_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LogiWeb`.`driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LogiWeb`.`driver` ;

CREATE TABLE IF NOT EXISTS `LogiWeb`.`driver` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(18) NULL,
  `hours` SMALLINT UNSIGNED NULL DEFAULT 0,
  `status` ENUM('REST', 'WORK', 'DRIVING') NOT NULL DEFAULT 'REST',
  `current_city` VARCHAR(51) NULL,
  `current_truck_id` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `current_truck_idx` (`current_truck_id` ASC) VISIBLE,
  CONSTRAINT `current_truck_id`
    FOREIGN KEY (`current_truck_id`)
    REFERENCES `LogiWeb`.`truck` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
